INSERT INTO CLASSROOM (classid, trainerName) VALUES (1, 'John Doe')
INSERT INTO CLASSROOM (classid, trainerName) VALUES (2, 'Jane Doe')
INSERT INTO CLASSROOM (classid, trainerName) VALUES (3, 'Jim Taylor')
INSERT INTO TRAINEE (id, traineeName) VALUES (1, 'hi Doe')
INSERT INTO TRAINEE (id, traineeName) VALUES (2, 'bye Doe')
INSERT INTO TRAINEE (id, traineeName) VALUES (3, 'ok Taylor')